apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-name
spec:
  replicas: 1
  template:
    metadata:
      labels:
        env: alpha
    spec:
      containers:
        - name: service-name
          resources:
            limits:
              cpu: 100m
              memory: 32Mi
            requests:
              cpu: 80m
              memory: 16Mi
