apiVersion: batch/v1
kind: CronJob
metadata:
  name: service-name
spec:
  schedule: "30 12 * * *"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: service-name
              image: localhost:5001/service-name
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: service-name
                - secretRef:
                    name: service-name
              resources:
                limits:
                  cpu: 200m
                  memory: 64Mi
                requests:
                  cpu: 100m
                  memory: 8Mi
          restartPolicy: Never
