apiVersion: batch/v1
kind: CronJob
metadata:
  name: service-name
spec:
  schedule: "30 12 * * *"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: service-name
              image: asia-southeast1-docker.pkg.dev/inari-non-prod/inari-registry/service-name:TAG
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: service-name
                - secretRef:
                    name: service-name
                - secretRef:
                    name: domain-common-secret
          restartPolicy: Never
          imagePullSecrets:
            - name: gcp-artifact-registry
