name: pr-checks

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.0"

      - name: Install dependencies
        run: go mod download

      - name: Run Unit Tests
        run: go test ./...

      - name: Build Go binary
        run: go build -o app
