name: service-name

services:
  app:
    container_name: service-name
    build:
      context: .
      dockerfile: ./build/docker/Dockerfile.dev
    volumes:
      - ./:/src/go
    ports:
      - 8080:8080
    working_dir: /src/go
    command: air -c .air.toml
    depends_on:
      - wiremock
    networks:
      - app-network

  wiremock:
    image: wiremock/wiremock:3.9.2
    container_name: wiremock
    ports:
      - 1324:8080
    volumes:
      - ./tools/wiremock/__files:/home/wiremock/__files
      - ./tools/wiremock/mappings:/home/wiremock/mappings
    networks:
      - app-network

  gripmock:
    image: tkpd/gripmock:v1.13
    container_name: gripmock
    ports:
      - 4770:4770
    volumes:
      - ./tools/gripmock/proto:/proto
      - ./tools/gripmock/stub:/stub
    command: ["--stub=/stub", "/proto/auth.proto"]
    networks:
      - app-network

networks:
  app-network:
    external: true
