fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        stages: [commit]
      - id: trailing-whitespace
        stages: [commit]
      - id: check-merge-conflict
        stages: [commit]
      - id: check-yaml
        args: [--allow-multiple-documents]
        stages: [commit]
      - id: detect-private-key
        stages: [commit]

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: golangci-lint-repo-mod
        stages: [commit]
      - id: go-test-mod
        stages: [commit]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.16.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
