basePath: '{{.BasePath}}'
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: API Endpoints for service-name
  version: "1.0"
paths:
  /v1/example:
    get:
      description: Run DoExample function
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Run DoExample function
  /v1/test:
    get:
      description: Run DoWiremock function
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Run DoWiremock function
swagger: "2.0"
