apiVersion: v1
kind: Service
metadata:
  name: service-name
  labels:
    app.kubernetes.io/name: service-name
    app.kubernetes.io/instance: service-name
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: service-name
    app.kubernetes.io/instance: service-name
