name: service-name

services:
  app:
    container_name: service-name
    build:
      context: .
      dockerfile: ./build/docker/Dockerfile.dev
    volumes:
      - ./:/src/go
    ports:
      - 8080:8080
    working_dir: /src/go/server/clean-http-polyrepo
    command: air -c .air.toml
    networks:
      - app-network

networks:
  app-network:
    external: true
