apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alpha

resources:
  - ../../base

images:
  - name: localhost:5001/service-name
    newName: localhost:5001/service-name
    newTag: latest

patchesStrategicMerge:
  - set_resources.yaml

configMapGenerator:
  - name: service-name
    envs:
      - config.env

secretGenerator:
  - name: service-name
    envs:
      - secrets.env

generatorOptions:
  disableNameSuffixHash: true
