apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-name
  labels:
    app.kubernetes.io/name: service-name
    app.kubernetes.io/instance: service-name
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: service-name
      app.kubernetes.io/instance: service-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: service-name
        app.kubernetes.io/instance: service-name
    spec:
      containers:
        - name: service-name
          image: localhost:5001/service-name
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: service-name
            - secretRef:
                name: service-name
            - secretRef:
                name: domain-common-secret
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 10
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 10
            initialDelaySeconds: 10
