apiVersion: v1
kind: Service
metadata:
  name: service-name
  labels:
    app.kubernetes.io/name: service-name
    app.kubernetes.io/instance: service-name
spec:
  selector:
    app.kubernetes.io/name: service-name
    app.kubernetes.io/instance: service-name
