apiVersion: batch/v1
kind: Job
metadata:
  name: service-name
spec:
  ttlSecondsAfterFinished: 604800
  template:
    containers:
      - name: service-name
        image: localhost:5001/service-name
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: service-name
          - secretRef:
              name: service-name
          - secretRef:
              name: domain-common-secret
    restartPolicy: Never
