apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

patchesStrategicMerge:
  - deployment_replica.yaml

configMapGenerator:
  - name: servicename
    envs:
      - prod.env

generatorOptions:
  disableNameSuffixHash: true
