apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

patchesStrategicMerge:
  - set_resources.yaml

configMapGenerator:
  - name: service-name
    envs:
      - config.env

secretGenerator:
  - name: service-name
    envs:
      - secrets.env

generatorOptions:
  disableNameSuffixHash: tru