apiVersion: batch/v1
kind: Job
metadata:
  name: service-name
spec:
  template:
    metadata:
      labels:
        app: service-name
        env: alpha
    spec:
      containers:
        - name: service-name
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
