apiVersion: v1
kind: Service
metadata:
  name: servicename
spec:
  selector:
    app: servicename
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
