apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alpha

resources:
  - ../../base

images:
  - name: asia-southeast1-docker.pkg.dev/inari-non-prod/inari-registry/service-name
    newName: asia-southeast1-docker.pkg.dev/inari-non-prod/inari-registry/service-name
    newTag: latest

patchesStrategicMerge:
  - set_resources.yaml

configMapGenerator:
  - name: service-name
    envs:
      - config.env

secretGenerator:
  - name: service-name
    envs:
      - secret.env

generatorOptions:
  disableNameSuffixHash: true
