apiVersion: batch/v1
kind: CronJob
metadata:
  name: service-name
spec:
  schedule: "00 19 * * *"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      metadata:
        labels:
          app: service-name
          env: alpha
      containers:
        - name: service-name
          resources:
            limits:
              cpu: 100m
              memory: 32Mi
            requests:
              cpu: 80m
              memory: 16Mi
