apiVersion: v1
kind: Service
metadata:
  name: domain-service
spec:
  selector:
    app: domain-service
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
