apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

secretGenerator:
  - name: domain-name-common-secret
    envs:
      - secret.env

generatorOptions:
  disableNameSuffixHash: 