name: service-name

services:
  app:
    container_name: service-name
    build:
      context: .
      dockerfile: ./build/docker/Dockerfile.dev
    volumes:
      - ./:/src/go
    ports:
      - 8080:8080
    working_dir: /src/go
    command: air -c .air.toml
    depends_on:
      - postgres
      - redis
      - kafka
      - wiremock
    networks:
      - app-network

  postgres:
    image: postgres:14.15-alpine3.20
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: test
      TZ: Asia/Bangkok
    ports:
      - 5432:5432
    volumes:
      - ./.docker-volumes/postgres:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7.4.0
    container_name: redis
    ports:
      - 6379:6379
    command: >
      --requirepass 1234
    networks:
      - app-network

  zookeeper:
    image: bitnami/zookeeper:3.9.3
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-network

  kafka:
    image: bitnami/kafka:3.7.1
    container_name: kafka
    ports:
      - 9094:9094
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=BROKER:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      - KAFKA_CFG_LISTENERS=BROKER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=BROKER://kafka:9093,EXTERNAL://localhost:9094
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=BROKER
      - KAFKA_INTER_BROKER_USER=inter_broker_user
      - KAFKA_INTER_BROKER_PASSWORD=inter_broker_password
      - KAFKA_CLIENT_LISTENER_NAME=EXTERNAL
      - KAFKA_CLIENT_USERS=admin
      - KAFKA_CLIENT_PASSWORDS=1234
    depends_on:
      - zookeeper
    networks:
      - app-network

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    environment:
      KAFKA_BROKERS: kafka:9093
      KAFKA_SASL_ENABLED: "true"
      KAKFA_SASL_MECHANISM: PLAIN
      KAFKA_SASL_USERNAME: admin
      KAFKA_SASL_PASSWORD: 1234
      KAFKA_SECURITY_PROTOCOL: SASL_PLAINTEXT
    ports:
      - 8100:8080
    depends_on:
      - kafka
    networks:
      - app-network

  wiremock:
    image: wiremock/wiremock:3.9.2
    container_name: wiremock
    ports:
      - 1324:8080
    volumes:
      - ./tools/wiremock/__files:/home/wiremock/__files
      - ./tools/wiremock/mappings:/home/wiremock/mappings
    networks:
      - app-network

networks:
  app-network:
    external: true
