apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

patchesStrategicMerge:
  - deployment_replica.yaml

configMapGenerator:
  - name: domain-service
    envs:
      - dev.env

secretGenerator:
  - name: domain-service
    envs:
      - dev.secrets.env

generatorOptions:
  disableNameSuffixHash: true
