basePath: /server
host: '{{.Host}}'
info:
  contact: {}
  description: This is the API documentation for clean-http
  license: {}
  title: API Endpoints for clean-http
  version: "1.0"
paths:
  /v1/example:
    get:
      description: Run DoExample function
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Run DoExample function
swagger: "2.0"
