apiVersion: batch/v1
kind: Job
metadata:
  name: service-name
spec:
  template:
    metadata:
      labels:
        app: service-name
        env: prod
    spec:
      containers:
        - name: service-name
          resources:
            limits:
              cpu: 100m
              memory: 32Mi
            requests:
              cpu: 80m
              memory: 16Mi
